#!/usr/bin/env bash
# Generate the secrets for the first install (cloud/deploy/README.md, section "Secrets").
#
# Usage:
#   cloud/deploy/k3s/make-secrets.sh <output.yaml outside the repository> <public base URL>
#
#   <public base URL>  for example https://<machine>.<tailnet>.ts.net
#
# Writes to <output.yaml> (mode 600), and never inside the repository:
#   - reify-postgres-auth and reify-platform-secrets (namespace reify-system)
#       JWT_PRIVATE_KEY      ES256 key that signs user access tokens
#       GATEWAY_PRIVATE_KEY  second ES256 key that signs the 60 s gateway tokens
#       DATABASE_URL, POSTGRES_PASSWORD (one random password, used in both)
# Prints to stdout the ConfigMap reify-gateway-pubkey (namespace reify-ws) with the public half of
# GATEWAY_PRIVATE_KEY. Apply it with kubectl. It is never the JWT public key.
#
# Existing output files are not overwritten. Private keys live in a temporary directory that is
# removed on exit.
set -euo pipefail
umask 077

usage() {
  echo "usage: $(basename "$0") <output.yaml outside the repository> <public base URL, https://...>" >&2
  exit 2
}

[ $# -eq 2 ] || usage
OUT="$1"
BASE="${2%/}"
case "$BASE" in
  https://*) ;;
  *) echo "the public base URL must start with https://" >&2; exit 2 ;;
esac
command -v openssl >/dev/null 2>&1 || { echo "openssl not found" >&2; exit 1; }

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(git -C "$HERE" rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$REPO" ] || REPO="$(cd "$HERE/../../.." && pwd)"

OUT_ABS="$(realpath -m -- "$OUT")"
case "$OUT_ABS" in
  "$REPO"|"$REPO"/*)
    echo "refusing to write inside the repository: $OUT_ABS" >&2
    echo "choose a path such as /root/reify-secrets.yaml" >&2
    exit 1
    ;;
esac
[ ! -e "$OUT_ABS" ] || { echo "refusing to overwrite $OUT_ABS" >&2; exit 1; }
[ -d "$(dirname "$OUT_ABS")" ] || { echo "directory does not exist: $(dirname "$OUT_ABS")" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

ec_pair() { # name -> $WORK/name-private.pem, $WORK/name-public.pem
  openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$WORK/$1-private.pem"
  openssl pkey -in "$WORK/$1-private.pem" -pubout -out "$WORK/$1-public.pem"
}
ec_pair jwt
ec_pair gateway

PW="$(openssl rand -hex 24)"
indent() { sed 's/^/    /' "$1"; }

cat > "$OUT_ABS" <<EOF
# Generated by cloud/deploy/k3s/make-secrets.sh. Contains real secrets. Keep it outside the repository.
apiVersion: v1
kind: Secret
metadata:
  name: reify-postgres-auth
  namespace: reify-system
  labels:
    app.kubernetes.io/part-of: reify
type: Opaque
stringData:
  POSTGRES_USER: reify
  POSTGRES_DB: reify
  POSTGRES_PASSWORD: $PW
---
apiVersion: v1
kind: Secret
metadata:
  name: reify-platform-secrets
  namespace: reify-system
  labels:
    app.kubernetes.io/part-of: reify
type: Opaque
stringData:
  DATABASE_URL: postgres://reify:$PW@postgres.reify-system.svc.cluster.local:5432/reify?sslmode=disable
  JWT_PRIVATE_KEY: |
$(indent "$WORK/jwt-private.pem")
  GATEWAY_PRIVATE_KEY: |
$(indent "$WORK/gateway-private.pem")
  PUBLIC_BASE_URL: $BASE
EOF
chmod 600 "$OUT_ABS"

cat <<EOF
# reify-gateway-pubkey: public half of GATEWAY_PRIVATE_KEY. Apply after the namespace reify-ws exists:
#   kubectl apply -f <this output>
apiVersion: v1
kind: ConfigMap
metadata:
  name: reify-gateway-pubkey
  namespace: reify-ws
  labels:
    app.kubernetes.io/part-of: reify
data:
  gateway-public-key.pem: |
$(indent "$WORK/gateway-public.pem")
EOF

echo "wrote $OUT_ABS (mode 600). It holds the signing keys and the database password. Back it up outside the repository, then apply it and delete the local copy." >&2
