import { test, expect, _electron as electron } from "@playwright/test";
import { chmod, cp, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { glob } from "node:fs/promises";
import extract from "extract-zip";

async function showWorkspaceMode(page: import("@playwright/test").Page, mode: "conversation" | "canvas") {
  const shell = page.locator(".workbench-page");
  const current = (await shell.getAttribute("class")) || "";
  if (!current.includes(`mode-${mode}`)) await page.keyboard.press("Control+Backslash");
  await expect(shell).toHaveClass(new RegExp(`mode-${mode}`));
}

test("complete desktop product path", async () => {
  const nativeRoot = await mkdtemp(join(tmpdir(), "pi-cad-e2e-"));
  const appRoot = join(nativeRoot, "app");
  const electronRoot = join(nativeRoot, "electron");
  await mkdir(appRoot, { recursive: true });
  await cp(join(process.cwd(), "out"), join(appRoot, "out"), { recursive: true });
  await mkdir(join(appRoot, "node_modules"), { recursive: true });
  await cp(join(process.cwd(), "node_modules/yaml"), join(appRoot, "node_modules/yaml"), { recursive: true });
  const cacheRoot = join(process.env.LOCALAPPDATA || "", "electron", "Cache");
  let electronZip = "";
  for await (const candidate of glob(join(cacheRoot, "**/electron-v*-win32-x64.zip"))) { electronZip = candidate; break; }
  let executablePath = join(process.cwd(), "node_modules/electron/dist/electron.exe");
  if (electronZip) { await extract(electronZip, { dir: electronRoot }); executablePath = join(electronRoot, "electron.exe"); }
  await chmod(executablePath, 0o755);
  await writeFile(join(appRoot, "package.json"), JSON.stringify({ name: "pi-cad-e2e", version: "0.0.0", type: "module", main: "out/main/index.js" }));
  const application = await electron.launch({ executablePath, args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", `--user-data-dir=${join(nativeRoot, "user-data")}`, appRoot, "--pi-cad-e2e", "--pi-cad-e2e-open-step=/workspace/demo/imported.step"], env: { ...process.env, PI_CAD_DESKTOP_E2E: "1", PI_CAD_PROJECT_CWD: "/workspace/demo" } });
  const page = await application.firstWindow();
  const pageErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error" && !/WebGL context/i.test(message.text())) pageErrors.push(message.text());
    console.log(`[renderer:${message.type()}] ${message.text()}`);
  });
  page.on("pageerror", (error) => { pageErrors.push(error.message); console.error(`[renderer:error] ${error.message}`); });
  await page.waitForLoadState("domcontentloaded", { timeout: 30_000 });
  await expect(page.getByText("MAKE IDEAS REAL")).toBeVisible();
  await expect(page.getByRole("button", { name: "进入 Reify" })).toBeEnabled();
  await page.getByRole("button", { name: "进入 Reify" }).click();
  await expect(page.getByText("Reify").first()).toBeVisible();
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByTestId("conversation")).toBeVisible();
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-conversation/);

  const cancellationComposer = page.getByPlaceholder("Ask anything about the design");
  await cancellationComposer.fill("Long calculation");
  await cancellationComposer.press("Enter");
  await expect(page.getByRole("button", { name: "Stop" })).toBeVisible();
  await cancellationComposer.fill("First queued modification");
  await cancellationComposer.press("Enter");
  await cancellationComposer.fill("Second queued modification");
  await cancellationComposer.press("Enter");
  const queued = page.getByRole("region", { name: "Pending requests" }).getByRole("textbox");
  await expect(queued).toHaveCount(2);
  await queued.nth(1).fill("Second queued modification, edited");
  await cancellationComposer.fill("A queued request to cancel");
  await cancellationComposer.press("Enter");
  await expect(queued).toHaveCount(3);
  await page.getByRole("region", { name: "Pending requests" }).getByRole("button", { name: /Cancel queued request/ }).last().click();
  await expect(queued).toHaveCount(2);
  await page.getByLabel("Running request action").selectOption("note");
  await cancellationComposer.fill("Keep the mounting face unchanged");
  await cancellationComposer.press("Enter");
  await expect(page.getByText("Note · Keep the mounting face unchanged")).toHaveCount(1);
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByText("Note · Keep the mounting face unchanged")).toBeVisible();
  await page.getByLabel("Running request action").selectOption("queue");
  await expect(page.getByText("Model built", { exact: true })).toHaveCount(3, { timeout: 10_000 });
  await expect(page.getByRole("region", { name: "Pending requests" })).toHaveCount(0);

  await cancellationComposer.fill("Long calculation to stop");
  await cancellationComposer.press("Enter");
  await expect(page.getByRole("button", { name: "Stop" })).toBeVisible();
  await page.getByLabel("Running request action").selectOption("replace");
  await cancellationComposer.fill("Build a compact bracket");
  await page.getByRole("button", { name: "Stop and modify" }).click();
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByText("Stopped")).toBeVisible();
  await expect(page.getByText("Model built", { exact: true })).toHaveCount(4);
  await expect(page.getByRole("button", { name: "Send" })).toBeVisible();
  await showWorkspaceMode(page, "conversation");

  const firstComposer = page.getByPlaceholder("Ask anything about the design");
  await firstComposer.fill("Generate concept directions");
  await firstComposer.press("Enter");
  await expect(page.getByRole("region", { name: "Concept board" })).toBeVisible();
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-canvas/);
  await page.getByRole("button", { name: "Zoom in" }).click();
  await expect(page.getByRole("region", { name: "Concept board" }).locator("output")).toHaveText("115%");
  const concept = page.locator(".concept-image").first();
  const conceptBounds = await concept.boundingBox();
  expect(conceptBounds).not.toBeNull();
  await page.mouse.move(conceptBounds!.x + conceptBounds!.width * .2, conceptBounds!.y + conceptBounds!.height * .2);
  await page.mouse.down();
  await page.mouse.move(conceptBounds!.x + conceptBounds!.width * .7, conceptBounds!.y + conceptBounds!.height * .7);
  await page.mouse.up();
  await expect(page.locator(".concept-board-status")).toContainText("region selected");
  await page.getByLabel("Annotation for concept 1").fill("Keep the low, stable base.");
  await page.getByRole("button", { name: "Mark outdated" }).click();
  await expect(page.getByRole("button", { name: "Use this direction" })).toBeDisabled();
  await page.getByRole("button", { name: "Restore" }).click();
  await page.getByRole("button", { name: "Use this direction" }).click();
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await expect(page.getByRole("button", { name: "Send" })).toBeVisible();
  await page.getByRole("button", { name: "Concepts" }).click();
  await expect(page.getByLabel("Annotation for concept 1")).toHaveValue("Keep the low, stable base.");
  await showWorkspaceMode(page, "conversation");

  await page.locator(".chat-header .open-step").click();
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-canvas/);
  await expect(page.locator(".viewer-file-identity")).toContainText("imported.step");
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByTestId("conversation")).toBeVisible();
  await page.waitForTimeout(150);
  await showWorkspaceMode(page, "canvas");
  await showWorkspaceMode(page, "conversation");
  await page.getByLabel("Permission").selectOption("read-only");
  await expect(page.getByLabel("Permission")).toHaveValue("read-only");
  await page.getByLabel("Permission").selectOption("workspace");
  await page.getByLabel("Model").selectOption("gpt-5.6-luna");
  await page.getByLabel("Effort").selectOption("low");
  await expect(page.getByLabel("Model")).toHaveValue("gpt-5.6-luna");
  await expect(page.getByLabel("Effort")).toHaveValue("low");
  const protectedDraft = page.getByPlaceholder("Ask anything about the design");
  await protectedDraft.fill("Keep this draft");
  await page.evaluate(async () => { await window.piCad.runtime.start(); await window.piCad.runtime.prompt("Build while I am drafting"); });
  await expect(page.getByRole("button", { name: /New model ready/ })).toBeVisible();
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-conversation/);
  await expect(protectedDraft).toHaveValue("Keep this draft");
  await expect(page.locator(".viewer-file-identity")).toContainText("imported.step");
  await protectedDraft.fill("");
  await page.getByRole("button", { name: /New model ready/ }).click();
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-canvas/);
  await showWorkspaceMode(page, "canvas");
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-canvas/);

  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(920, 680));
  await page.waitForTimeout(200);
  await expect(page.locator(".cad-viewer")).toBeVisible();
  await expect(page.getByPlaceholder("Ask anything about the design")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(1440, 900));
  await page.waitForTimeout(200);

  const composer = page.getByPlaceholder("Ask anything about the design");
  await composer.fill("Build a compact bracket");
  await composer.press("Enter");
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-canvas/);
  await expect(page.getByText("Model built", { exact: true })).not.toHaveCount(0);
  await showWorkspaceMode(page, "conversation");
  await expect(page.locator(".design-pane")).toBeHidden();
  await expect(page.locator(".cad-viewer-open-source .tcv_cad_navigation")).toBeHidden();
  await expect(page.locator(".cad-viewer-open-source .tcv_cad_toolbar")).toBeHidden();
  await expect(page.getByText("Build a compact bracket", { exact: true })).toBeVisible();
  await expect(page.getByText("Model built", { exact: true }).last()).toBeVisible();
  await expect(page.getByText("The first model is built and ready for inspection.").last()).toBeVisible();
  await page.getByPlaceholder("Ask anything about the design").fill("Inspect image");
  await showWorkspaceMode(page, "conversation");
  expect(await page.locator(".conversation").evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
  await expect(page.locator(".activity-media img:visible").first()).toBeVisible();
  await page.locator(".activity-media img:visible").first().click();
  await expect(page.getByRole("dialog", { name: "Tool image preview" })).toBeVisible();
  await page.getByRole("dialog", { name: "Tool image preview" }).click();
  await page.getByPlaceholder("Ask anything about the design").fill("");
  await showWorkspaceMode(page, "canvas");
  const unavailable = page.getByText("3D preview unavailable", { exact: true });
  if (await unavailable.isVisible()) {
    await expect(unavailable).toBeVisible();
  } else {
    await expect(page.locator(".cad-viewer-open-source .tcv_cad_body")).toBeVisible();
    await expect(page.locator(".cad-viewer-open-source canvas")).toBeVisible();
  }
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await expect(page.locator(".viewer-file-identity code")).toHaveText("demo-step");
  await expect(page.getByRole("button", { name: "Export copy" })).toBeVisible();
  const artifacts = page.getByRole("complementary", { name: "Artifacts" });
  await expect(artifacts).toContainText("current · authoritative-candidate-design");
  await artifacts.getByRole("button", { name: "Results" }).click();
  await expect(artifacts).toContainText("static-check · stress");
  const visualArtifact = artifacts.locator("button").filter({ hasText: "image · tool output" }).first();
  await expect(visualArtifact).toBeVisible();
  await visualArtifact.click();
  const artifactPreview = page.getByRole("dialog", { name: "Artifact preview" });
  await expect(artifactPreview).toBeVisible();
  await expect(artifactPreview.getByRole("button", { name: "Reference in conversation" })).toBeVisible();
  await artifactPreview.getByRole("button", { name: "Back to model" }).click();
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await artifacts.getByRole("button", { name: "Models" }).click();
  await expect(artifacts).not.toContainText("static-check · stress");
  const quickInspect = page.getByRole("complementary", { name: "Quick inspection" });
  await quickInspect.getByRole("button", { name: "X", exact: true }).first().click();
  await expect(quickInspect).toContainText("Bounding box · X 40 mm · Y 24 mm · Z 12 mm · 3 solids");
  await expect(quickInspect).toContainText("SHA demo-step");
  await quickInspect.getByRole("button", { name: "Z", exact: true }).last().click();
  await expect(quickInspect).toContainText("Section Z at 6 mm · area 960 mm² · 1 faces");
  await quickInspect.getByRole("button", { name: "Reference in conversation" }).click();
  await expect(page.getByRole("button", { name: "Send" })).toBeVisible();
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByText(/Reference this measured result.*Section Z.*SHA-256 demo-step.*Do not modify/)).toBeVisible();
  await showWorkspaceMode(page, "canvas");
  await expect(page.getByTestId("parameter-panel")).toBeVisible();
  await expect(page.getByTestId("parameter-panel")).toContainText("Source ·");
  await expect(page.getByTestId("parameter-panel")).toContainText("Applied · 40 mm");
  await expect(page.getByTestId("parameter-panel")).toContainText("Range");
  const fillet = page.getByRole("spinbutton", { name: "Fillet radius" });
  await fillet.fill("10");
  await expect(page.getByText("Failed candidate", { exact: false })).toBeVisible();
  await expect(page.getByTestId("parameter-panel")).toContainText("Fillet radius is too large");
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await page.getByRole("button", { name: "Restore applied values" }).click();
  await expect(fillet).toHaveValue("1");
  const width = page.getByRole("spinbutton", { name: "Width" });
  await width.fill("64");
  await expect(page.locator(".parameter-status")).toContainText("Preview ready");
  await page.getByRole("button", { name: "Reset preview" }).click();
  await expect(width).toHaveValue("40");
  await expect(page.locator(".parameter-status")).toContainText("Up to date");
  await width.fill("64");
  await expect(page.locator(".parameter-status")).toContainText("Preview ready");
  await page.getByRole("button", { name: "Apply" }).click();
  await expect(page.locator(".parameter-status")).toContainText("Applied");
  await page.screenshot({ path: join(process.cwd(), "test-results", "workbench-parameters.png") });
  await page.screenshot({ path: join(process.cwd(), "test-results", "workbench-model.png") });
  await page.getByLabel("Viewer source").first().selectOption({ label: "static-check · stress" });
  await expect(page.getByText("ParaView session ready")).toBeVisible();
  await expect(page.getByText("von Mises stress · 2.4–82 MPa")).toBeVisible();
  await expect(page.getByText("Model · build/part.step#demo-step")).toBeVisible();
  await page.screenshot({ path: join(process.cwd(), "test-results", "workbench-simulation.png") });
  await page.getByLabel("Viewer source").first().selectOption({ label: "authoritative candidate design" });
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await page.getByLabel("Viewer source").first().selectOption({ label: "static-check · stress" });
  await page.getByRole("button", { name: "Compare" }).click();
  await expect(page.locator(".viewer-scene")).toHaveCount(2);
  await page.screenshot({ path: join(process.cwd(), "test-results", "workbench-compare.png") });

  await page.getByRole("button", { name: "Workflows" }).click();
  await expect(page.getByRole("heading", { name: "mechanical.one-shot" })).toBeVisible();
  await page.getByRole("button", { name: /concept/i }).click();
  await expect(page.getByText("image.generate")).toBeVisible();
  await page.getByRole("button", { name: "New workflow" }).click();
  await expect(page.getByRole("heading", { name: "custom.workflow" })).toBeVisible();
  await page.getByRole("button", { name: "Save workflow" }).click();
  await expect(page.getByText("Saved and validated")).toBeVisible();

  await page.getByRole("button", { name: "Workbench" }).click();
  await expect(page.getByRole("spinbutton", { name: "Width" })).toHaveValue("64");

  await page.getByRole("button", { name: "Trajectories" }).click();
  await expect(page.getByText("Folding stand")).toBeVisible();
  await page.getByText("Folding stand").click();
  await expect(page.getByText("I checked the interfaces before building.")).toBeVisible();
  await expect(page.locator(".trace-check")).toHaveClass(/selected/);
  const traceFooter = page.locator(".trace-list footer");
  await traceFooter.getByRole("button", { name: "1 selected" }).click();
  await traceFooter.getByLabel("Quality").selectOption("2");
  await traceFooter.getByLabel("Difficulty").selectOption("4");
  await traceFooter.getByPlaceholder("What worked or failed?").fill("The hinge direction was wrong.");
  await traceFooter.getByRole("button", { name: "Rate 1" }).click();
  await expect(page.locator(".rating-status")).toContainText("Rating saved");
  await expect(page.locator(".trace-row").filter({ hasText: "Folding stand" })).toContainText("2/5");
  await page.getByRole("button", { name: "Distill now" }).click();
  await expect(page.getByText(/Experience updated · quality 2\/5/)).toBeVisible();

  await page.getByRole("button", { name: "Workbench" }).click();
  await showWorkspaceMode(page, "conversation");
  const recoveryComposer = page.getByPlaceholder("Ask anything about the design");
  await recoveryComposer.fill("Simulate interruption");
  await recoveryComposer.press("Enter");
  await expect(page.getByRole("alert").filter({ hasText: "Task was interrupted" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Retry runtime" })).toBeVisible();
  await page.getByRole("button", { name: "Continue task" }).click();
  await expect(page.getByText("Model built", { exact: true }).last()).toBeVisible();

  await page.getByRole("button", { name: "Settings" }).click();
  await expect(page.getByText("ChatGPT connected")).toBeVisible();
  await page.getByRole("button", { name: "Workbench" }).click();
  await showWorkspaceMode(page, "canvas");
  await page.getByPlaceholder("Ask anything about the design").fill("Draft survives restart");
  await page.reload();
  await expect(page.locator(".workbench-page")).toHaveClass(/mode-canvas/);
  await expect(page.getByPlaceholder("Ask anything about the design")).toHaveValue("Draft survives restart");
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByText(/Build a compact bracket/)).toBeVisible();
  await page.evaluate(async () => { await window.piCad.runtime.stop(); await window.piCad.settings.update({ projectPath: "/workspace/second-project" }); });
  await page.reload();
  await expect(page.getByPlaceholder("Ask anything about the design")).toHaveValue("");
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await expect(page.getByText(/Build a compact bracket/)).toHaveCount(0);
  await page.evaluate(async () => { await window.piCad.runtime.stop(); await window.piCad.settings.update({ projectPath: "/workspace/demo" }); });
  await page.reload();
  await expect(page.getByPlaceholder("Ask anything about the design")).toHaveValue("Draft survives restart");
  await expect(page.locator(".viewer-file-identity")).toContainText("part.step");
  await page.getByRole("button", { name: "Rename Folding stand" }).click();
  await page.getByLabel("Conversation title for Folding stand").fill("Bracket review");
  await page.getByLabel("Conversation title for Folding stand").press("Enter");
  await expect(page.getByText("Bracket review", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "新对话" }).click();
  await expect(page.getByTestId("conversation")).not.toContainText("I checked the interfaces before building.");
  await expect(page.locator(".session-menu")).toHaveCount(0);
  await page.getByText("Bracket review", { exact: true }).click();
  await expect(page.getByText("I checked the interfaces before building.")).toBeVisible();
  await page.locator(".chat-header .open-step").click();
  await expect(page.getByTestId("parameter-unbound")).toBeVisible();
  await page.getByRole("button", { name: "Ask Agent to modify" }).click();
  await expect(page.getByRole("button", { name: "Send" })).toBeVisible();
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByText(/Modify the selected CAD model at .*imported\.step/)).toBeVisible();
  await showWorkspaceMode(page, "canvas");
  const assemblyTree = page.getByRole("complementary", { name: "Assembly tree" });
  await expect(assemblyTree).toContainText("frame · 2 solids");
  await expect(assemblyTree).toContainText("pin · 1 solid");
  await assemblyTree.locator(".assembly-part").filter({ hasText: "frame" }).click();
  await expect(assemblyTree).toContainText("Selected · frame · version demo-step");
  await assemblyTree.getByRole("button", { name: "Hide Bracket frame" }).click();
  await expect(assemblyTree.getByRole("button", { name: "Show Bracket frame" })).toBeVisible();
  await assemblyTree.getByRole("button", { name: "Isolate Bracket pin" }).click();
  await expect(assemblyTree.getByText("Unisolate", { exact: true })).toBeVisible();
  await assemblyTree.getByRole("button", { name: "Show all" }).click();
  await assemblyTree.getByRole("button", { name: "Ask Agent to modify" }).click();
  await expect(page.getByRole("button", { name: "Send" })).toBeVisible();
  await showWorkspaceMode(page, "canvas");
  await expect(assemblyTree).toContainText("Selected · frame · version demo-step");
  await showWorkspaceMode(page, "conversation");
  await expect(page.getByText(/partId=frame.*Preserve this stable part identity/)).toBeVisible();
  await showWorkspaceMode(page, "canvas");
  const analysis = page.getByRole("complementary", { name: "Structural analysis" });
  await analysis.getByRole("button", { name: "Structural analysis" }).click();
  const poisson = analysis.getByRole("spinbutton", { name: "Poisson ratio" });
  await poisson.fill("0.6");
  await expect(analysis.getByRole("alert")).toContainText("between -1 and 0.5");
  await expect(analysis.getByRole("button", { name: "Confirm and run" })).toBeDisabled();
  await poisson.fill("0.33");
  await analysis.getByRole("spinbutton", { name: "Z force" }).fill("-120");
  await analysis.getByRole("button", { name: "Confirm and run" }).click();
  await showWorkspaceMode(page, "canvas");
  await analysis.getByRole("button", { name: "Stop analysis" }).click();
  await expect(analysis.getByRole("button", { name: "Confirm and run" })).toBeEnabled();
  await analysis.getByRole("button", { name: "Confirm and run" }).click();
  await expect(page.getByTestId("activity-simulation").first()).toContainText("Simulation stopped");
  await expect(page.getByTestId("activity-simulation").last()).toContainText("Simulation complete");
  await expect(page.getByTestId("activity-simulation").last()).toContainText("0.34 mm");
  await expect(page.getByTestId("activity-simulation").last()).toContainText("82 MPa");
  await expect(page.getByText(/reaction-balance and mesh-refinement checks/)).toBeVisible();
  expect(pageErrors).toEqual([]);
  await application.close();
  await rm(nativeRoot, { recursive: true, force: true, maxRetries: 8, retryDelay: 250 });
});
