# Analysis Situs v2024.2 (BSD-3-Clause) sources compiled into reify-asi.
# Paths are relative to the AnalysisSitus src/ directory (ASI_SRC).
# Generated from the include closure of the algorithm entry points, USE_MOBIUS=OFF.
set(ASI_SOURCES
  asiActiveData/API/ActAPI_IAlgorithm.cpp
  asiActiveData/API/ActAPI_ILogger.cpp
  asiActiveData/API/ActAPI_IPlotter.cpp
  asiActiveData/API/ActAPI_IProgressNotifier.cpp
  asiActiveData/API/ActAPI_Variables.cpp
  asiActiveData/Mesh/DS/ActData_Mesh.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Direction.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Edge.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Element.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_ElementsIterator.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Face.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_IDFactory.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_MapOfMeshOrientedElement.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Node.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Position.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Quadrangle.cpp
  asiActiveData/Mesh/DS/ActData_Mesh_Triangle.cpp
  asiAlgo/appsurf/asiAlgo_BuildCoonsSurf.cpp
  asiAlgo/auxiliary/asiAlgo_BVHAlgo.cpp
  asiAlgo/auxiliary/asiAlgo_BVHFacets.cpp
  asiAlgo/auxiliary/asiAlgo_BVHIterator.cpp
  asiAlgo/auxiliary/asiAlgo_CheckThickness.cpp
  asiAlgo/auxiliary/asiAlgo_CheckValidity.cpp
  asiAlgo/auxiliary/asiAlgo_Classifier.cpp
  asiAlgo/auxiliary/asiAlgo_ClassifyPointFace.cpp
  asiAlgo/auxiliary/asiAlgo_HitFacet.cpp
  asiAlgo/auxiliary/asiAlgo_Utils.cpp
  asiAlgo/blends/asiAlgo_AttrBlendCandidate.cpp
  asiAlgo/blends/asiAlgo_FindCrossEdges.cpp
  asiAlgo/blends/asiAlgo_FindSmoothEdges.cpp
  asiAlgo/blends/asiAlgo_FindSpringEdges.cpp
  asiAlgo/blends/asiAlgo_FindTermEdges.cpp
  asiAlgo/blends/asiAlgo_RecognizeBlends.cpp
  asiAlgo/blends/asiAlgo_RecognizeEBF.cpp
  asiAlgo/blends/asiAlgo_RecognizeVBF.cpp
  asiAlgo/canrec/asiAlgo_ConvertCanonical.cpp
  asiAlgo/canrec/asiAlgo_ConvertCanonicalCurve.cpp
  asiAlgo/canrec/asiAlgo_ConvertCanonicalMod.cpp
  asiAlgo/canrec/asiAlgo_ConvertCanonicalSummary.cpp
  asiAlgo/canrec/asiAlgo_ConvertCanonicalSurface.cpp
  asiAlgo/canrec/asiAlgo_RecognizeCanonical.cpp
  asiAlgo/discr/asiAlgo_DiscrBuilder.cpp
  asiAlgo/discr/asiAlgo_DiscrClassifier2d.cpp
  asiAlgo/discr/asiAlgo_DiscrCurve.cpp
  asiAlgo/discr/asiAlgo_DiscrCurve2d.cpp
  asiAlgo/discr/asiAlgo_DiscrCurveAdaptor.cpp
  asiAlgo/discr/asiAlgo_DiscrEdge.cpp
  asiAlgo/discr/asiAlgo_DiscrFace.cpp
  asiAlgo/discr/asiAlgo_DiscrModel.cpp
  asiAlgo/discr/asiAlgo_DiscrParams.cpp
  asiAlgo/discr/asiAlgo_DiscrTessellateCurve.cpp
  asiAlgo/discr/asiAlgo_DiscrWire.cpp
  asiAlgo/editing/asiAlgo_BRepNormalization.cpp
  asiAlgo/editing/asiAlgo_BRepNormalizer.cpp
  asiAlgo/editing/asiAlgo_History.cpp
  asiAlgo/editing/asiAlgo_Naming.cpp
  asiAlgo/features/asiAlgo_AAG.cpp
  asiAlgo/features/asiAlgo_AAGIterator.cpp
  asiAlgo/features/asiAlgo_AdjacencyMx.cpp
  asiAlgo/features/asiAlgo_CheckDihedralAngle.cpp
  asiAlgo/features/asiAlgo_ExtractFeatures.cpp
  asiAlgo/features/asiAlgo_ExtractFeaturesResult.cpp
  asiAlgo/features/asiAlgo_FeatureFaces.cpp
  asiAlgo/features/asiAlgo_FindFeatureHints.cpp
  asiAlgo/features/asiAlgo_Isomorphism.cpp
  asiAlgo/features/asiAlgo_RecognizeCavities.cpp
  asiAlgo/features/asiAlgo_RecognizeCavitiesRule.cpp
  asiAlgo/features/asiAlgo_RecognizeDrillHoles.cpp
  asiAlgo/features/asiAlgo_RecognizeDrillHolesRule.cpp
  asiAlgo/features/asiAlgo_Recognizer.cpp
  asiAlgo/features/asiAlgo_TopoGraph.cpp
  asiAlgo/interop/asiAlgo_FileFormat.cpp
  asiAlgo/interop/asiAlgo_IGES.cpp
  asiAlgo/interop/asiAlgo_PLY.cpp
  asiAlgo/mesh/asiAlgo_MeshCheckTopology.cpp
  asiAlgo/mesh/asiAlgo_MeshComputeShapeNorms.cpp
  asiAlgo/mesh/asiAlgo_MeshInfo.cpp
  asiAlgo/mesh/asiAlgo_MeshMerge.cpp
  asiAlgo/points/asiAlgo_BaseCloud.cpp
  asiAlgo/points/asiAlgo_PointCloudUtils.cpp
  asiAlgo/points/asiAlgo_RelievePointCloud.cpp
  asiAlgo/utils/asiAlgo_JSON.cpp
)
