// Original transfer-export spool and equivalence checker over disposable files.
// FreeCAD canonicalization/inspection and the local Fusion executable boundary
// are synthetic. The native dispatcher, installer, uploads and checks are real.
import {mkdirSync,writeFileSync,readFileSync,existsSync,readdirSync,rmSync as requireRm} from 'node:fs';
import {join,dirname} from 'node:path';
import {spawn} from 'node:child_process';
export function fusionFixture(home,repo,files,audit){
 let mode='normal';const roots=new Map();
 function root(project){const id=project.split('/').at(-1),dir=join(home,'fusion-projects',id);if(!roots.has(id)){mkdirSync(join(dir,'parts'),{recursive:true});writeFileSync(join(dir,'parts/bracket.FCStd'),'Synthetic FreeCAD document');writeFileSync(join(dir,'parts/arm.FCStd'),'Synthetic FreeCAD assembly');roots.set(id,dir)}return dir}
 function put(project,path,bytes){if(!path.startsWith('build/transfer')&&!path.startsWith('.pi-cad/transfer')&&!path.startsWith('exports/'))return;const f=join(root(project),path);mkdirSync(dirname(f),{recursive:true});writeFileSync(f,bytes)}
 function get(project,path){const f=join(root(project),path);return existsSync(f)&&!path.includes('..')?readFileSync(f):null}
 function execute(r,project,done){const q=JSON.parse(r.input),dir=root(project);if(q.source&&files.has(q.source)){const f=join(dir,q.source);mkdirSync(dirname(f),{recursive:true});writeFileSync(f,files.get(q.source));}if(q.operation==='metadata'&&files.has(q.path)&&!q.path.startsWith('.pi-cad/transfer/')){const target=join(dir,q.path);mkdirSync(dirname(target),{recursive:true});writeFileSync(target,files.get(q.path));}let script=r.args[r.args.indexOf('-e')+1];script=script.replaceAll('/opt/reify/pi-cad',repo);if(script.includes('REIFY_TRANSFER_VIEW')){const inspector=`const inspector={inspectGeometry:async(root,path)=>({ok:true,payload:{bbox:{x:40,y:30,z:5},volume:${mode==='displayed-mismatch'?'path.endsWith("reference.step")?6000:5000':'6000'},faceFingerprints:[{type:'PLANE',c:[20,15,5],a:1200,n:[0,0,1]},{type:'PLANE',c:[20,15,0],a:1200,n:[0,0,-1]}]}})};`;script=script.replace(`const inspector=await jiti.import('${repo}/src/shared/capability.ts');`,inspector);}const child=spawn(process.execPath,['-e',script],{cwd:repo}),out=[],err=[];child.stdout.on('data',x=>out.push(x));child.stderr.on('data',x=>err.push(x));child.on('close',code=>{audit.push({type:script.includes('REIFY_TRANSFER_VIEW')?'fusion-display-check':'fusion-io',op:q.operation,path:q.path,project,mode,report:script.includes('REIFY_TRANSFER_VIEW')&&code===0?JSON.parse(Buffer.concat(out).toString()):undefined});done({code,stdout:Buffer.concat(out).toString(),stderr:Buffer.concat(err).toString()})});child.stdin.end(JSON.stringify({...q,root:dir}));}
 function agent(q,project,done){const dir=root(project),snapshot=mode;
  if(q.op==='part-open'||q.op==='part-apply'){const doc=join(dir,q.doc);mkdirSync(dirname(doc),{recursive:true});writeFileSync(doc,JSON.stringify(q));audit.push({type:'fusion-agent',request:q,project,mode:snapshot});done({code:0,stdout:JSON.stringify({schema:1,ok:true,result:{ok:true}}),stderr:''});return}
  const script=`(async()=>{const fs=require('fs'),p=require('path'),jiti=require(${JSON.stringify(repo+'/node_modules/jiti')}).createJiti(${JSON.stringify(repo+'/package.json')});const {handleTransferOperation,transferHooks}=await jiti.import(${JSON.stringify(repo+'/src/agent-api/transfer-ops.ts')});const q=${JSON.stringify(q)},cwd=${JSON.stringify(dir)},mode=${JSON.stringify(snapshot)};transferHooks.pollMs=50;let simulated=Date.now();if(mode==='timeout'){transferHooks.now=()=>simulated;transferHooks.sleep=async()=>{simulated+=200000;await new Promise(r=>setTimeout(r,50))}};
  transferHooks.canonicalize=async(cwd,doc,reference)=>{fs.writeFileSync(reference,'Synthetic reference STEP');const assembly=doc.includes('arm'),features=assembly?{schema:'reify.assembly/1',part:'arm',occurrences:[{id:'left',pose:[0,0,0]},{id:'right',pose:[20,0,0]}],reference:{feature_volumes:[{name:'plate/base',volume_mm3:6000}]}}:{schema:'reify.features/1',part:'plate',bodies:[],reference:{feature_volumes:[{name:'plate/base',volume_mm3:6000}]}};return {kind:assembly?'assembly':'part',features,featureCount:assembly?2:6,part:assembly?'arm':'plate',joints:assembly?[{path:'arm/hinge',type:'revolute',value:0}]:[]}};
  transferHooks.inspect=async(cwd,path)=>({bbox:{x:40,y:30,z:5},volume:mode==='shape-fail'&&!path.endsWith('reference.step')?5000:6000,faceFingerprints:[{type:'PLANE',c:[20,15,5],a:1200,n:[0,0,1]},{type:'PLANE',c:[20,15,0],a:1200,n:[0,0,-1]}]});
  try{console.log(JSON.stringify({schema:1,ok:true,result:await handleTransferOperation(cwd,q)}))}catch(e){console.log(JSON.stringify({schema:1,ok:false,error:{message:e.message,code:e.code,target:e.target,detail:e.detail,hints:e.hints}}));process.exitCode=1}})().catch(e=>{console.error(e);process.exitCode=1});`;
  const child=spawn(process.execPath,['-e',script],{cwd:repo}),out=[],err=[];child.stdout.on('data',x=>out.push(x));child.stderr.on('data',x=>err.push(x));child.on('close',code=>{const stdout=Buffer.concat(out).toString();audit.push({type:'fusion-agent',request:q,project,mode:snapshot,code,response:JSON.parse(stdout)});done({code,stdout,stderr:Buffer.concat(err).toString()})});
 }
 function scopeRequests(project,session,enabled){const dir=root(project);for(const [id,scope] of [['native-old-scope','another-conversation'],['native-unbound-scope',undefined]]){const path=join(dir,'.pi-cad/transfer/requests',id+'.json');if(!enabled){try{requireRm(path)}catch{};continue}mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify({schema:'reify.transfer.request/1',jobId:id,target:'fusion',features:'old.features.json',native:'exports/old.f3d',...(scope?{sessionId:scope}:{})}));}}
 return {execute,agent,put,get,root,scopeRequests,get mode(){return mode},set mode(v){mode=v}};
}
