#!/usr/bin/env bash
# Installs the optional FreeCAD part backend (conda-forge FreeCAD in a private
# prefix). Never uses sudo and never touches shell configuration files.
#
# Usage: bash scripts/bootstrap-freecad.sh [--force]
# Exit codes: 0 ok, 2 unsupported platform, 3 download verification failed,
#             4 environment creation failed, 5 smoke test failed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

# micromamba is taken from the conda-forge channel (the same host that serves
# the FreeCAD packages), pinned by version and SHA-256.
MICROMAMBA_VERSION="2.9.0"
MICROMAMBA_BUILD="0"
MICROMAMBA_SHA256_LINUX_64="8761c382127e6363bd9e0a2451aa3ef90d071a79133f736e2f759a3bf13040dd"
MICROMAMBA_SHA256_OSX_ARM64="500f5074feb8d02c4296ef9921c3650ed2874171805a9fbb8fbb53896433646b"
CHANNEL_URL="${PI_CAD_CONDA_CHANNEL_URL:-https://conda.anaconda.org/conda-forge}"

os="$(uname -s)"
arch="$(uname -m)"
case "$os/$arch" in
  Linux/x86_64)
    PLATFORM="linux-64"
    MICROMAMBA_SHA256="$MICROMAMBA_SHA256_LINUX_64"
    DEFAULT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/pi-cad/runtimes/freecad"
    ;;
  Darwin/arm64)
    PLATFORM="osx-arm64"
    MICROMAMBA_SHA256="$MICROMAMBA_SHA256_OSX_ARM64"
    DEFAULT_HOME="$HOME/Library/Application Support/pi-cad/runtimes/freecad"
    ;;
  *)
    echo "[pi-cad] FreeCAD backend supports Linux x86_64 (including WSL) and macOS arm64 only; found $os/$arch" >&2
    exit 2
    ;;
esac

FREECAD_HOME="${PI_CAD_FREECAD_HOME:-$DEFAULT_HOME}"
ENV_DIR="$FREECAD_HOME/env"
RUNTIME_JSON="$FREECAD_HOME/runtime.json"
MICROMAMBA="$FREECAD_HOME/bin/micromamba"
LOCK="$ROOT/python/runtimes/freecad/conda-$PLATFORM.lock"
ENV_YML="$ROOT/python/runtimes/freecad/environment.yml"
PYTHON_BIN="$ENV_DIR/bin/python"
LIB_DIR="$ENV_DIR/lib"

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

# FreeCAD.so lives in <env>/lib, which is not on sys.path by default.
smoke_test() {
  PYTHONPATH="$ROOT/python:$LIB_DIR" "$PYTHON_BIN" -c \
    "import FreeCAD, Part, Sketcher, PartDesign; print('FreeCAD', '.'.join(FreeCAD.Version()[:3]))"
  if [ -f "$ROOT/python/reify_freecad/selftest.py" ]; then
    PYTHONPATH="$ROOT/python:$LIB_DIR" "$PYTHON_BIN" -m reify_freecad.selftest
  fi
}

write_runtime_json() {
  PYTHONPATH="$ROOT/python:$LIB_DIR" "$PYTHON_BIN" - "$RUNTIME_JSON" "$PYTHON_BIN" "$LIB_DIR" "$PLATFORM" <<'PY'
import json, sys
import FreeCAD, Part
from datetime import datetime as _dt, timezone as _tz
path, python, lib, platform = sys.argv[1:5]
version = ".".join(FreeCAD.Version()[:3])
occt = getattr(Part, "OCC_VERSION", None) or "unknown"
json.dump({
    "schema": 1, "python": python, "libPath": lib, "freecadVersion": version,
    "occtVersion": str(occt), "platform": platform,
    "installedAt": _dt.now(_tz.utc).isoformat(),
}, open(path, "w"), indent=2)
open(path, "a").write("\n")
PY
}

mkdir -p "$FREECAD_HOME/bin"

if [ "$FORCE" = 1 ]; then
  rm -rf "$ENV_DIR" "$RUNTIME_JSON"
fi

if [ -x "$PYTHON_BIN" ] && [ -f "$RUNTIME_JSON" ]; then
  echo "[pi-cad] FreeCAD runtime already installed at $FREECAD_HOME; re-running the smoke test"
  smoke_test || { echo "[pi-cad] smoke test failed; re-run with --force" >&2; exit 5; }
  exit 0
fi

if [ ! -x "$MICROMAMBA" ]; then
  archive="$(mktemp "${TMPDIR:-/tmp}/pi-cad-micromamba.XXXXXX")"
  trap 'rm -f "$archive"' EXIT
  url="$CHANNEL_URL/$PLATFORM/micromamba-$MICROMAMBA_VERSION-$MICROMAMBA_BUILD.tar.bz2"
  echo "[pi-cad] downloading micromamba $MICROMAMBA_VERSION"
  curl -fsSL "$url" -o "$archive"
  actual="$(sha256_of "$archive")"
  if [ "$actual" != "$MICROMAMBA_SHA256" ]; then
    echo "[pi-cad] micromamba checksum mismatch (expected $MICROMAMBA_SHA256, got $actual)" >&2
    exit 3
  fi
  scratch="$(mktemp -d "${TMPDIR:-/tmp}/pi-cad-micromamba-x.XXXXXX")"
  tar -xjf "$archive" -C "$scratch" bin/micromamba
  mv "$scratch/bin/micromamba" "$MICROMAMBA"
  rm -rf "$scratch"
  chmod +x "$MICROMAMBA"
fi

export MAMBA_ROOT_PREFIX="$FREECAD_HOME/mamba-root"
rm -rf "$ENV_DIR"
if [ -f "$LOCK" ]; then
  echo "[pi-cad] creating FreeCAD environment from $(basename "$LOCK")"
  "$MICROMAMBA" create -y -p "$ENV_DIR" --file "$LOCK" || { echo "[pi-cad] environment creation failed" >&2; exit 4; }
else
  echo "[pi-cad] warning: no lock file for $PLATFORM; solving environment.yml (not reproducible)" >&2
  "$MICROMAMBA" create -y -p "$ENV_DIR" -f "$ENV_YML" -c conda-forge || { echo "[pi-cad] environment creation failed" >&2; exit 4; }
fi
if [ "$PLATFORM" = "osx-arm64" ]; then
  echo "[pi-cad] note: the osx-arm64 lock file was generated by the solver and is not install-tested" >&2
fi

smoke_test || { echo "[pi-cad] FreeCAD smoke test failed" >&2; exit 5; }
# The download cache holds every package a second time; the environment is hard-linked, not symlinked.
"$MICROMAMBA" clean --all --yes >/dev/null 2>&1 || true
smoke_test >/dev/null || { echo "[pi-cad] FreeCAD smoke test failed after cleaning the package cache" >&2; exit 5; }
write_runtime_json
echo "[pi-cad] FreeCAD part backend installed: $FREECAD_HOME"
