"""Compile canonical flow/thermal specs into SU2 configuration files.

This is the "interpreter" half of the thermal/fluid story: Pi-CAD keeps a
canonical context (explicit geometry units, SI physical quantities, surface
selectors) and this module compiles it into the SU2 world. It adds no
physics of its own: every quantity in the generated cfg comes from the spec
or from a documented, fixed numerical scheme constant. Unknown spec keys are
rejected upstream (fail closed), so the compiler can assume a validated
spec.

Unit contract (frozen):
* CAD geometry is interpreted per ``geometryUnits`` (mm by default) and the
  mesh handed to SU2 is always in meters.
* Every physical quantity in the spec is SI with the unit in its name
  (``totalPressurePa``, ``temperatureK``, ...). No implicit mm->m conversion
  ever happens inside the solver input.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any

FLOW_PHYSICS_TYPES = ("compressible_euler", "compressible_rans", "incompressible_ns", "incompressible_rans")
TURBULENCE_MODELS = ("sa", "sst")

# Fixed, probe-validated numerics for the V1 steady walking skeleton. These
# are scheme choices, not physics: they do not encode operating conditions.
_CFL_COMPRESSIBLE = 2.0
_CFL_INCOMPRESSIBLE = 10.0


class ConfigCompileError(ValueError):
    pass


def _fmt(value: float) -> str:
    return repr(float(value))


def _direction(vector: Any, where: str) -> list[float]:
    if not isinstance(vector, (list, tuple)) or len(vector) != 3:
        raise ConfigCompileError(f"{where} must be a numeric 3-vector")
    try:
        v = [float(x) for x in vector]
    except (TypeError, ValueError):
        raise ConfigCompileError(f"{where} must be a numeric 3-vector")
    norm = math.sqrt(sum(c * c for c in v))
    if norm < 1e-12:
        raise ConfigCompileError(f"{where} must be a non-zero direction")
    return [c / norm for c in v]


def _sutherland_viscosity(temperature_k: float) -> float:
    """Sutherland law for air (kg/(m*s)); used only to derive the Reynolds
    initialization scale for compressible RANS runs."""
    return 1.458e-6 * temperature_k**1.5 / (temperature_k + 110.4)


def _header(lines: list[str]) -> None:
    lines.extend(
        [
            "%",
            "% Generated by Pi-CAD (canonical spec -> SU2 cfg).",
            "% Quantities are SI; the mesh is in meters.",
            "%",
        ]
    )


def _check_full_coverage(spec: dict[str, Any], all_markers: list[str]) -> None:
    """Every boundary surface of the fluid domain must be classified exactly
    once; an unclassified or double-classified surface would silently change
    the physical problem SU2 sees."""
    seen: dict[str, int] = {}
    for index, boundary in enumerate(spec.get("boundaries") or []):
        for surface in boundary.get("surfaces") or []:
            if surface in seen:
                raise ConfigCompileError(
                    f"surface {surface} is classified by both boundaries[{seen[surface]}] "
                    f"and boundaries[{index}]"
                )
            seen[surface] = index
    uncovered = [m for m in all_markers if m not in seen]
    if uncovered:
        raise ConfigCompileError(
            f"every boundary surface of the fluid domain must be classified; uncovered: {sorted(uncovered)}"
        )
    unknown = [s for s in seen if s not in all_markers]
    if unknown:
        raise ConfigCompileError(
            f"boundary surfaces not present on this artifact version: {sorted(unknown)}"
        )


def compile_flow_cfg(
    spec: dict[str, Any],
    mesh_filename: str,
    domain_length_m: float,
    all_markers: list[str],
) -> str:
    physics = spec["physics"]
    physics_type = physics["type"]
    fluid = spec["fluid"]
    boundaries = spec["boundaries"]
    initial = spec.get("initial") or {}
    convergence = spec.get("convergence") or {}
    max_iterations = int(convergence.get("maxIterations", 2000))
    _check_full_coverage(spec, all_markers)

    lines: list[str] = []
    _header(lines)

    if physics_type not in FLOW_PHYSICS_TYPES:
        raise ConfigCompileError(f"unsupported flow physics type {physics_type!r}")
    compressible = physics_type.startswith("compressible_")
    rans = physics_type.endswith("_rans")

    solver = {
        "compressible_euler": "EULER",
        "compressible_rans": "RANS",
        "incompressible_ns": "INC_NAVIER_STOKES",
        "incompressible_rans": "INC_RANS",
    }[physics_type]
    lines.append(f"SOLVER= {solver}")
    lines.append("MATH_PROBLEM= DIRECT")
    lines.append("RESTART_SOL= NO")
    lines.append(f"MESH_FILENAME= {mesh_filename}")
    lines.append("MESH_FORMAT= SU2")

    if rans:
        turbulence = physics.get("turbulence")
        if turbulence not in TURBULENCE_MODELS:
            raise ConfigCompileError("RANS physics requires turbulence in {sa, sst}")
        lines.append(f"KIND_TURB_MODEL= {turbulence.upper()}")

    if compressible:
        if fluid.get("model") != "ideal_gas":
            raise ConfigCompileError("compressible flow requires fluid.model= ideal_gas in V1")
        gamma = float(fluid.get("gamma", 0.0))
        gas_constant = float(fluid.get("gasConstantJPerKgK", 0.0))
        if not (1.0 < gamma <= 2.0):
            raise ConfigCompileError("fluid.gamma must be in (1, 2]")
        if gas_constant <= 0:
            raise ConfigCompileError("fluid.gasConstantJPerKgK must be > 0")
        lines.append("FLUID_MODEL= IDEAL_GAS")
        lines.append(f"GAMMA_VALUE= {_fmt(gamma)}")
        lines.append(f"GAS_CONSTANT= {_fmt(gas_constant)}")

        mach = float(initial.get("mach", 0.0))
        temperature = float(initial.get("temperatureK", 0.0))
        pressure = float(initial.get("pressurePa", 0.0))
        if mach <= 0 or temperature <= 0 or pressure <= 0:
            raise ConfigCompileError(
                "compressible flow requires initial mach, temperatureK, and pressurePa > 0"
            )
        lines.append(f"MACH_NUMBER= {_fmt(mach)}")
        lines.append(f"FREESTREAM_TEMPERATURE= {_fmt(temperature)}")
        lines.append(f"FREESTREAM_PRESSURE= {_fmt(pressure)}")
        if rans:
            density = pressure / (gas_constant * temperature)
            speed_of_sound = math.sqrt(gamma * gas_constant * temperature)
            reynolds = density * mach * speed_of_sound * domain_length_m / _sutherland_viscosity(temperature)
            lines.append(f"REYNOLDS_NUMBER= {_fmt(reynolds)}")
            lines.append(f"REYNOLDS_LENGTH= {_fmt(domain_length_m)}")
    else:
        if fluid.get("model") != "constant_density":
            raise ConfigCompileError("incompressible flow requires fluid.model= constant_density in V1")
        density = float(fluid.get("densityKgPerM3", 0.0))
        viscosity = float(fluid.get("dynamicViscosityPas", 0.0))
        if density <= 0 or viscosity <= 0:
            raise ConfigCompileError("fluid.densityKgPerM3 and dynamicViscosityPas must be > 0")
        velocity = float(initial.get("velocityMPerS", 0.0))
        if velocity <= 0:
            raise ConfigCompileError("incompressible flow requires initial velocityMPerS > 0")
        lines.append("INC_NONDIM= DIMENSIONAL")
        lines.append("INC_DENSITY_MODEL= CONSTANT")
        lines.append(f"INC_DENSITY_REF= {_fmt(density)}")
        lines.append("VISCOSITY_MODEL= CONSTANT_VISCOSITY")
        lines.append(f"MU_CONSTANT= {_fmt(viscosity)}")
        lines.append("INC_ENERGY_EQUATION= NO")
        lines.append(f"INC_VELOCITY_INIT= {_fmt(velocity)}, 0.0, 0.0")
        lines.append("INC_INLET_TYPE= VELOCITY_INLET")
        lines.append("INC_OUTLET_TYPE= PRESSURE_OUTLET")

    inlets: list[str] = []
    outlets: list[str] = []
    walls: list[str] = []
    slip_walls: list[str] = []
    turb_inlets: list[str] = []
    turbulence_inlet = spec.get("turbulenceInlet") or {}
    for index, boundary in enumerate(boundaries):
        where = f"boundaries[{index}]"
        kind = boundary.get("type")
        surfaces = boundary.get("surfaces") or []
        if not surfaces:
            raise ConfigCompileError(f"{where}.surfaces must list at least one surface ID")
        if kind == "total_conditions_inlet":
            if not compressible:
                raise ConfigCompileError(
                    f"{where}: total_conditions_inlet requires compressible physics in V1"
                )
            direction = _direction(boundary.get("flowDirection"), f"{where}.flowDirection")
            total_pressure = float(boundary.get("totalPressurePa", 0.0))
            total_temperature = float(boundary.get("totalTemperatureK", 0.0))
            if total_pressure <= 0 or total_temperature <= 0:
                raise ConfigCompileError(f"{where}: totalPressurePa and totalTemperatureK must be > 0")
            for surface in surfaces:
                inlets.append(
                    f"{surface}, {_fmt(total_temperature)}, {_fmt(total_pressure)}, "
                    f"{direction[0]}, {direction[1]}, {direction[2]}"
                )
                if rans:
                    intensity = float(turbulence_inlet.get("intensity", 0.05))
                    viscosity_ratio = float(turbulence_inlet.get("viscosityRatio", 10.0))
                    if not (0.0 < intensity < 1.0) or viscosity_ratio <= 0:
                        raise ConfigCompileError(
                            "turbulenceInlet.intensity must be in (0,1) and viscosityRatio > 0"
                        )
                    turb_inlets.append(f"{surface}, {_fmt(intensity)}, {_fmt(viscosity_ratio)}")
        elif kind == "velocity_inlet":
            if compressible:
                raise ConfigCompileError(f"{where}: velocity_inlet requires incompressible physics in V1")
            direction = _direction(boundary.get("flowDirection"), f"{where}.flowDirection")
            velocity = float(boundary.get("velocityMPerS", 0.0))
            temperature = float(boundary.get("temperatureK", 0.0))
            if velocity <= 0 or temperature <= 0:
                raise ConfigCompileError(f"{where}: velocityMPerS and temperatureK must be > 0")
            for surface in surfaces:
                inlets.append(
                    f"{surface}, {_fmt(temperature)}, {_fmt(velocity)}, "
                    f"{direction[0]}, {direction[1]}, {direction[2]}"
                )
                if rans:
                    intensity = float(turbulence_inlet.get("intensity", 0.05))
                    viscosity_ratio = float(turbulence_inlet.get("viscosityRatio", 10.0))
                    if not (0.0 < intensity < 1.0) or viscosity_ratio <= 0:
                        raise ConfigCompileError(
                            "turbulenceInlet.intensity must be in (0,1) and viscosityRatio > 0"
                        )
                    turb_inlets.append(f"{surface}, {_fmt(intensity)}, {_fmt(viscosity_ratio)}")
        elif kind == "pressure_outlet":
            static_pressure = float(boundary.get("staticPressurePa", 0.0))
            if static_pressure < 0:
                raise ConfigCompileError(f"{where}: staticPressurePa must be >= 0 (gauge for incompressible)")
            for surface in surfaces:
                outlets.append(f"{surface}, {_fmt(static_pressure)}")
        elif kind == "wall":
            thermal = boundary.get("thermal", "adiabatic")
            if thermal == "adiabatic":
                flux = 0.0
            elif isinstance(thermal, dict) and "heatFluxWPerM2" in thermal:
                if not compressible or physics_type == "compressible_euler":
                    # Euler (inviscid) and isothermal incompressible V1 have no
                    # wall heat-flux pathway; reject instead of dropping it.
                    raise ConfigCompileError(
                        f"{where}: wall heat flux requires compressible_rans in V1"
                    )
                flux = float(thermal["heatFluxWPerM2"])
            else:
                raise ConfigCompileError(f"{where}: wall thermal must be 'adiabatic' or {{heatFluxWPerM2}}")
            for surface in surfaces:
                if physics_type == "compressible_euler":
                    slip_walls.append(surface)
                else:
                    walls.append(f"{surface}, {_fmt(flux)}")
        else:
            raise ConfigCompileError(f"{where}: unsupported boundary type {kind!r} in V1")

    if not inlets:
        raise ConfigCompileError("flow spec requires at least one inlet boundary")
    if not outlets:
        raise ConfigCompileError("flow spec requires at least one outlet boundary")

    lines.append("MARKER_INLET= ( " + ", ".join(inlets) + " )")
    lines.append("MARKER_OUTLET= ( " + ", ".join(outlets) + " )")
    if slip_walls:
        lines.append("MARKER_EULER= ( " + ", ".join(slip_walls) + " )")
    if walls:
        lines.append("MARKER_HEATFLUX= ( " + ", ".join(walls) + " )")
    if turb_inlets:
        lines.append("MARKER_INLET_TURBULENT= ( " + ", ".join(turb_inlets) + " )")

    # Numerics (fixed V1 scheme).
    lines.append("NUM_METHOD_GRAD= GREEN_GAUSS")
    if compressible:
        lines.append("CONV_NUM_METHOD_FLOW= ROE")
        lines.append("MUSCL_FLOW= YES")
        lines.append("SLOPE_LIMITER_FLOW= NONE")
        lines.append(f"CFL_NUMBER= {_fmt(_CFL_COMPRESSIBLE)}")
        lines.append("TIME_DISCRE_FLOW= EULER_IMPLICIT")
        if rans:
            lines.append("CONV_NUM_METHOD_TURB= SCALAR_UPWIND")
            lines.append("MUSCL_TURB= NO")
            lines.append("SLOPE_LIMITER_TURB= NONE")
            lines.append("TIME_DISCRE_TURB= EULER_IMPLICIT")
    else:
        lines.append("CONV_NUM_METHOD_FLOW= FDS")
        lines.append("MUSCL_FLOW= NO")
        lines.append(f"CFL_NUMBER= {_fmt(_CFL_INCOMPRESSIBLE)}")
        lines.append("TIME_DISCRE_FLOW= EULER_IMPLICIT")
        if rans:
            lines.append("CONV_NUM_METHOD_TURB= SCALAR_UPWIND")
            lines.append("MUSCL_TURB= NO")
            lines.append("SLOPE_LIMITER_TURB= NONE")
            lines.append("TIME_DISCRE_TURB= EULER_IMPLICIT")

    lines.append(f"ITER= {max_iterations}")
    # Convergence is evaluated by Pi-CAD from history.csv (uniform across
    # solvers); SU2's own convergence tokens are solver-dependent.
    lines.append("OUTPUT_FILES= ( PARAVIEW, CSV )")
    lines.append("VOLUME_OUTPUT= (COORDINATES, SOLUTION, PRIMITIVE)")
    lines.append("SCREEN_OUTPUT= (ITER, RMS_RES)")
    return "\n".join(lines) + "\n"


def compile_thermal_cfg(spec: dict[str, Any], mesh_filename: str, all_markers: list[str]) -> str:
    material = spec["material"]
    boundaries = spec["boundaries"]
    convergence = spec.get("convergence") or {}
    max_iterations = int(convergence.get("maxIterations", 3000))

    lines: list[str] = []
    _header(lines)
    lines.append("SOLVER= HEAT_EQUATION")
    lines.append("MATH_PROBLEM= DIRECT")
    lines.append("RESTART_SOL= NO")
    lines.append(f"MESH_FILENAME= {mesh_filename}")
    lines.append("MESH_FORMAT= SU2")

    conductivity = float(material.get("conductivityWPerMK", 0.0))
    if conductivity <= 0:
        raise ConfigCompileError("material.conductivityWPerMK must be > 0")
    lines.append("FLUID_MODEL= IDEAL_GAS")
    lines.append("GAMMA_VALUE= 1.4")
    lines.append("GAS_CONSTANT= 287.05")
    lines.append("CONDUCTIVITY_MODEL= CONSTANT_CONDUCTIVITY")
    lines.append(f"THERMAL_CONDUCTIVITY_CONSTANT= {_fmt(conductivity)}")
    # Density and heat capacity do not enter the steady conduction equation;
    # fixed inert values keep the solver's transients well-posed.
    lines.append("MATERIAL_DENSITY= 1000.0")
    lines.append("SPECIFIC_HEAT_CP= 1000.0")
    lines.append("MACH_NUMBER= 0.0")

    isothermal: list[str] = []
    heatflux: list[str] = []
    dirichlet_anchors: list[tuple[str, float]] = []
    for index, boundary in enumerate(boundaries):
        where = f"boundaries[{index}]"
        kind = boundary.get("type")
        surfaces = boundary.get("surfaces") or []
        if not surfaces:
            raise ConfigCompileError(f"{where}.surfaces must list at least one surface ID")
        if kind == "temperature":
            temperature = float(boundary.get("temperatureK", 0.0))
            if temperature <= 0:
                raise ConfigCompileError(f"{where}: temperatureK must be > 0")
            for surface in surfaces:
                isothermal.append(f"{surface}, {_fmt(temperature)}")
                dirichlet_anchors.append((surface, temperature))
        elif kind == "heat_flux":
            flux = float(boundary.get("heatFluxWPerM2", 0.0))
            for surface in surfaces:
                heatflux.append(f"{surface}, {_fmt(flux)}")
        else:
            raise ConfigCompileError(f"{where}: unsupported thermal boundary type {kind!r} in V1")

    if not dirichlet_anchors:
        raise ConfigCompileError(
            "steady conduction requires at least one temperature boundary; "
            "an all-Neumann problem has no unique solution"
        )
    # Adiabatic remainder: surfaces of the solid left unclassified by the
    # spec are insulated (documented V1 semantics), so the cfg stays
    # complete without inventing thermal boundary conditions.
    covered = {surface for surface, _ in dirichlet_anchors}
    for boundary in boundaries:
        if boundary.get("type") == "heat_flux":
            covered.update(boundary.get("surfaces") or [])
    unknown = [s for s in covered if s not in all_markers]
    if unknown:
        raise ConfigCompileError(
            f"boundary surfaces not present on this artifact version: {sorted(unknown)}"
        )
    for surface in all_markers:
        if surface not in covered:
            heatflux.append(f"{surface}, 0.0")
    if isothermal:
        lines.append("MARKER_ISOTHERMAL= ( " + ", ".join(isothermal) + " )")
    if heatflux:
        lines.append("MARKER_HEATFLUX= ( " + ", ".join(heatflux) + " )")

    lines.append("ITER= %d" % max_iterations)
    lines.append("OUTPUT_FILES= ( PARAVIEW, CSV )")
    lines.append("VOLUME_OUTPUT= (COORDINATES, SOLUTION)")
    lines.append("SCREEN_OUTPUT= (ITER, RMS_RES)")
    return "\n".join(lines) + "\n"


def write_cfg(text: str, path: str | Path) -> str:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return str(path)
