-- Reify platform schema, phase 1 (plan §4). IDs are server-side UUIDs; times are timestamptz.
-- gen_random_uuid() is built in on PostgreSQL 13+, so no extension is needed.

create table users (
  id uuid primary key default gen_random_uuid(),
  email text not null,                 -- lowercased before storing
  display_name text,
  status text not null default 'active' check (status in ('active','disabled')),
  created_at timestamptz not null default now(),
  invite_id uuid,
  unique (email)
);
-- Email is the login method, not the identity. Other login methods later go in external_identities.
create table external_identities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  provider text not null,              -- 'password' in phase 1
  subject text not null,               -- for 'password': lowercased email
  created_at timestamptz not null default now(),
  unique (provider, subject)
);
create table teams (id uuid primary key default gen_random_uuid(), name text not null, personal_owner uuid references users(id), created_at timestamptz not null default now());
create table team_members (team_id uuid references teams(id), user_id uuid references users(id), role text not null check (role in ('owner','member')), primary key (team_id, user_id));
create table projects (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references teams(id),
  name text not null,
  created_by uuid not null references users(id),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create table project_members (project_id uuid references projects(id), user_id uuid references users(id), role text not null check (role in ('maintainer','editor','viewer')), primary key (project_id, user_id));

create table invites (
  id uuid primary key default gen_random_uuid(),
  token_hash bytea not null unique,    -- sha256(token); plaintext token is shown once at creation
  email text,                          -- null: any email may use it
  max_uses int not null default 1,
  used_count int not null default 0,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);
create table password_credentials (
  user_id uuid primary key references users(id),
  password_hash text not null,         -- argon2id
  updated_at timestamptz not null default now()
);
-- One-time reset links generated by reify-admin.
create table password_resets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  token_hash bytea not null unique,
  expires_at timestamptz not null,     -- 24 hours by default
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);
create table login_attempts (
  id bigserial primary key,
  email text not null,
  ip inet,
  ok boolean not null,
  at timestamptz not null default now()
);
create index on login_attempts (email, at desc);
create index on login_attempts (ip, at desc);   -- added: per-IP lockout lookup
create table refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id),
  token_hash bytea not null unique,
  device_label text,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  replaced_by uuid,
  created_at timestamptz not null default now()
);
create index on refresh_tokens (user_id);       -- added: revoke-all-for-user

create table workspaces (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references users(id),  -- one workspace per user
  k8s_name text not null unique,       -- 'ws-' || short id
  state text not null check (state in ('stopped','starting','running','stopping','failed')),
  desired text not null check (desired in ('running','stopped')),
  last_activity_at timestamptz,
  idle_warned_at timestamptz,
  state_changed_at timestamptz not null default now(),
  last_error text
);
create table sessions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id),
  prime_session_ref text not null,     -- relative path of the Prime session file inside the volume
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table events (
  id bigserial primary key,
  at timestamptz not null default now(),
  user_id uuid, project_id uuid, workspace_id uuid,
  kind text not null,                  -- 'login','invite_used','ws_start','ws_stop','ws_idle_warn','ws_reclaim','error',...
  detail jsonb not null default '{}'
);
create table legacy_ids (kind text not null, legacy text not null, id uuid not null, primary key (kind, legacy));
